feat(daylight savings time): handle daylight savings time
StatEngine/se-reporting pull request #5
Opened 2020-10-13 16:24 UTC by nathleia

2020-10-13 22:45 UTC, richard3d requested changes

2020-10-13 22:45 UTC, richard3d commented on src/index.js
> +function scheduleAll() {
Use parameter to tell if the schedule is DST? See comments below...

2020-10-13 22:45 UTC, richard3d commented on src/index.js
> +const startDstInterval = later.setInterval(scheduleAll, startDstSchedule);
As alluded to in the previous comment, the logic these two functions use are identical - you consider if a FD participates in DST but not if we are in DST according to the calendar date as well.

2020-10-13 22:45 UTC, richard3d commented on src/index.js
> +          if (isDst(deptId)) {
You consider if a FD participates in DST here but you do not consider if the calendar date is in DST when this runs.

2020-10-13 22:54 UTC, richard3d requested changes

2020-10-13 22:54 UTC, richard3d commented on src/index.js
> +timerStore.addInterval('startDst', startDstInterval);
Are these necessary to store in the timerStore?

2020-10-14 12:48 UTC, nathleia commented on src/index.js
> +          if (isDst(deptId)) {
the later.js schedules (startDstSchedule & endDstSchedule) are set to run on the exact days that DST starts and ends. i will add a second check using moment, but it may be superfluous.

2020-10-14 12:50 UTC, nathleia commented on src/index.js
> +function scheduleAll() {
startDstSchedule & endDstSchedule are already set to run on the days that DST begins and ends.

2020-10-14 13:09 UTC, nathleia commented on src/index.js
> +const startDstInterval = later.setInterval(scheduleAll, startDstSchedule);
startDstSchedule & endDstSchedule are created by later.js. they run on the days that daylight savings time starts and ends. will add the second check, but it may be superfluous.

2020-10-16 15:36 UTC, nathleia commented on src/index.js
> +function scheduleAll() {
used moment().isDST() to check if date is in DST

2020-10-29 20:53 UTC, merged